/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.kromatik.dasshy.thrift.model;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-06-13")
public class TBatchClockNBackoff implements org.apache.thrift.TBase<TBatchClockNBackoff, TBatchClockNBackoff._Fields>, java.io.Serializable, Cloneable, Comparable<TBatchClockNBackoff> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TBatchClockNBackoff");

  private static final org.apache.thrift.protocol.TField MAX_BATCHES_FIELD_DESC = new org.apache.thrift.protocol.TField("maxBatches", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField SLEEP_MS_FIELD_DESC = new org.apache.thrift.protocol.TField("sleepMs", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TBatchClockNBackoffStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TBatchClockNBackoffTupleSchemeFactory());
  }

  private int maxBatches; // required
  private long sleepMs; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MAX_BATCHES((short)1, "maxBatches"),
    SLEEP_MS((short)2, "sleepMs");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MAX_BATCHES
          return MAX_BATCHES;
        case 2: // SLEEP_MS
          return SLEEP_MS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MAXBATCHES_ISSET_ID = 0;
  private static final int __SLEEPMS_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MAX_BATCHES, new org.apache.thrift.meta_data.FieldMetaData("maxBatches", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SLEEP_MS, new org.apache.thrift.meta_data.FieldMetaData("sleepMs", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TBatchClockNBackoff.class, metaDataMap);
  }

  public TBatchClockNBackoff() {
  }

  public TBatchClockNBackoff(
    int maxBatches,
    long sleepMs)
  {
    this();
    this.maxBatches = maxBatches;
    setMaxBatchesIsSet(true);
    this.sleepMs = sleepMs;
    setSleepMsIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TBatchClockNBackoff(TBatchClockNBackoff other) {
    __isset_bitfield = other.__isset_bitfield;
    this.maxBatches = other.maxBatches;
    this.sleepMs = other.sleepMs;
  }

  public TBatchClockNBackoff deepCopy() {
    return new TBatchClockNBackoff(this);
  }

  @Override
  public void clear() {
    setMaxBatchesIsSet(false);
    this.maxBatches = 0;
    setSleepMsIsSet(false);
    this.sleepMs = 0;
  }

  public int getMaxBatches() {
    return this.maxBatches;
  }

  public void setMaxBatches(int maxBatches) {
    this.maxBatches = maxBatches;
    setMaxBatchesIsSet(true);
  }

  public void unsetMaxBatches() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __MAXBATCHES_ISSET_ID);
  }

  /** Returns true if field maxBatches is set (has been assigned a value) and false otherwise */
  public boolean isSetMaxBatches() {
    return EncodingUtils.testBit(__isset_bitfield, __MAXBATCHES_ISSET_ID);
  }

  public void setMaxBatchesIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __MAXBATCHES_ISSET_ID, value);
  }

  public long getSleepMs() {
    return this.sleepMs;
  }

  public void setSleepMs(long sleepMs) {
    this.sleepMs = sleepMs;
    setSleepMsIsSet(true);
  }

  public void unsetSleepMs() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SLEEPMS_ISSET_ID);
  }

  /** Returns true if field sleepMs is set (has been assigned a value) and false otherwise */
  public boolean isSetSleepMs() {
    return EncodingUtils.testBit(__isset_bitfield, __SLEEPMS_ISSET_ID);
  }

  public void setSleepMsIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SLEEPMS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MAX_BATCHES:
      if (value == null) {
        unsetMaxBatches();
      } else {
        setMaxBatches((Integer)value);
      }
      break;

    case SLEEP_MS:
      if (value == null) {
        unsetSleepMs();
      } else {
        setSleepMs((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MAX_BATCHES:
      return getMaxBatches();

    case SLEEP_MS:
      return getSleepMs();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MAX_BATCHES:
      return isSetMaxBatches();
    case SLEEP_MS:
      return isSetSleepMs();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TBatchClockNBackoff)
      return this.equals((TBatchClockNBackoff)that);
    return false;
  }

  public boolean equals(TBatchClockNBackoff that) {
    if (that == null)
      return false;

    boolean this_present_maxBatches = true;
    boolean that_present_maxBatches = true;
    if (this_present_maxBatches || that_present_maxBatches) {
      if (!(this_present_maxBatches && that_present_maxBatches))
        return false;
      if (this.maxBatches != that.maxBatches)
        return false;
    }

    boolean this_present_sleepMs = true;
    boolean that_present_sleepMs = true;
    if (this_present_sleepMs || that_present_sleepMs) {
      if (!(this_present_sleepMs && that_present_sleepMs))
        return false;
      if (this.sleepMs != that.sleepMs)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_maxBatches = true;
    list.add(present_maxBatches);
    if (present_maxBatches)
      list.add(maxBatches);

    boolean present_sleepMs = true;
    list.add(present_sleepMs);
    if (present_sleepMs)
      list.add(sleepMs);

    return list.hashCode();
  }

  @Override
  public int compareTo(TBatchClockNBackoff other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMaxBatches()).compareTo(other.isSetMaxBatches());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMaxBatches()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.maxBatches, other.maxBatches);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSleepMs()).compareTo(other.isSetSleepMs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSleepMs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sleepMs, other.sleepMs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TBatchClockNBackoff(");
    boolean first = true;

    sb.append("maxBatches:");
    sb.append(this.maxBatches);
    first = false;
    if (!first) sb.append(", ");
    sb.append("sleepMs:");
    sb.append(this.sleepMs);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!isSetMaxBatches()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'maxBatches' is unset! Struct:" + toString());
    }

    if (!isSetSleepMs()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'sleepMs' is unset! Struct:" + toString());
    }

    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TBatchClockNBackoffStandardSchemeFactory implements SchemeFactory {
    public TBatchClockNBackoffStandardScheme getScheme() {
      return new TBatchClockNBackoffStandardScheme();
    }
  }

  private static class TBatchClockNBackoffStandardScheme extends StandardScheme<TBatchClockNBackoff> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TBatchClockNBackoff struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MAX_BATCHES
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.maxBatches = iprot.readI32();
              struct.setMaxBatchesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SLEEP_MS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.sleepMs = iprot.readI64();
              struct.setSleepMsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TBatchClockNBackoff struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(MAX_BATCHES_FIELD_DESC);
      oprot.writeI32(struct.maxBatches);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SLEEP_MS_FIELD_DESC);
      oprot.writeI64(struct.sleepMs);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TBatchClockNBackoffTupleSchemeFactory implements SchemeFactory {
    public TBatchClockNBackoffTupleScheme getScheme() {
      return new TBatchClockNBackoffTupleScheme();
    }
  }

  private static class TBatchClockNBackoffTupleScheme extends TupleScheme<TBatchClockNBackoff> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TBatchClockNBackoff struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.maxBatches);
      oprot.writeI64(struct.sleepMs);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TBatchClockNBackoff struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.maxBatches = iprot.readI32();
      struct.setMaxBatchesIsSet(true);
      struct.sleepMs = iprot.readI64();
      struct.setSleepMsIsSet(true);
    }
  }

}

