/**
 * Dasshy - Real time Streaming and Batch Analytics Open Source System
 * Copyright (C) 2016 Kromatik Solutions
 *
 * This file is part of Dasshy
 *
 * Dasshy is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * Dasshy is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Dasshy.  If not, see <http://www.gnu.org/licenses/>.
 */
/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.kromatik.dasshy.thrift.model;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-06-13")
public class TBatchClockN implements org.apache.thrift.TBase<TBatchClockN, TBatchClockN._Fields>, java.io.Serializable, Cloneable, Comparable<TBatchClockN> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TBatchClockN");

  private static final org.apache.thrift.protocol.TField MAX_BATCHES_FIELD_DESC = new org.apache.thrift.protocol.TField("maxBatches", org.apache.thrift.protocol.TType.I32, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TBatchClockNStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TBatchClockNTupleSchemeFactory());
  }

  private int maxBatches; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MAX_BATCHES((short)1, "maxBatches");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MAX_BATCHES
          return MAX_BATCHES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MAXBATCHES_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MAX_BATCHES, new org.apache.thrift.meta_data.FieldMetaData("maxBatches", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TBatchClockN.class, metaDataMap);
  }

  public TBatchClockN() {
  }

  public TBatchClockN(
    int maxBatches)
  {
    this();
    this.maxBatches = maxBatches;
    setMaxBatchesIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TBatchClockN(TBatchClockN other) {
    __isset_bitfield = other.__isset_bitfield;
    this.maxBatches = other.maxBatches;
  }

  public TBatchClockN deepCopy() {
    return new TBatchClockN(this);
  }

  @Override
  public void clear() {
    setMaxBatchesIsSet(false);
    this.maxBatches = 0;
  }

  public int getMaxBatches() {
    return this.maxBatches;
  }

  public void setMaxBatches(int maxBatches) {
    this.maxBatches = maxBatches;
    setMaxBatchesIsSet(true);
  }

  public void unsetMaxBatches() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __MAXBATCHES_ISSET_ID);
  }

  /** Returns true if field maxBatches is set (has been assigned a value) and false otherwise */
  public boolean isSetMaxBatches() {
    return EncodingUtils.testBit(__isset_bitfield, __MAXBATCHES_ISSET_ID);
  }

  public void setMaxBatchesIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __MAXBATCHES_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MAX_BATCHES:
      if (value == null) {
        unsetMaxBatches();
      } else {
        setMaxBatches((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MAX_BATCHES:
      return getMaxBatches();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MAX_BATCHES:
      return isSetMaxBatches();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TBatchClockN)
      return this.equals((TBatchClockN)that);
    return false;
  }

  public boolean equals(TBatchClockN that) {
    if (that == null)
      return false;

    boolean this_present_maxBatches = true;
    boolean that_present_maxBatches = true;
    if (this_present_maxBatches || that_present_maxBatches) {
      if (!(this_present_maxBatches && that_present_maxBatches))
        return false;
      if (this.maxBatches != that.maxBatches)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_maxBatches = true;
    list.add(present_maxBatches);
    if (present_maxBatches)
      list.add(maxBatches);

    return list.hashCode();
  }

  @Override
  public int compareTo(TBatchClockN other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMaxBatches()).compareTo(other.isSetMaxBatches());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMaxBatches()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.maxBatches, other.maxBatches);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TBatchClockN(");
    boolean first = true;

    sb.append("maxBatches:");
    sb.append(this.maxBatches);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!isSetMaxBatches()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'maxBatches' is unset! Struct:" + toString());
    }

    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TBatchClockNStandardSchemeFactory implements SchemeFactory {
    public TBatchClockNStandardScheme getScheme() {
      return new TBatchClockNStandardScheme();
    }
  }

  private static class TBatchClockNStandardScheme extends StandardScheme<TBatchClockN> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TBatchClockN struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MAX_BATCHES
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.maxBatches = iprot.readI32();
              struct.setMaxBatchesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TBatchClockN struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(MAX_BATCHES_FIELD_DESC);
      oprot.writeI32(struct.maxBatches);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TBatchClockNTupleSchemeFactory implements SchemeFactory {
    public TBatchClockNTupleScheme getScheme() {
      return new TBatchClockNTupleScheme();
    }
  }

  private static class TBatchClockNTupleScheme extends TupleScheme<TBatchClockN> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TBatchClockN struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.maxBatches);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TBatchClockN struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.maxBatches = iprot.readI32();
      struct.setMaxBatchesIsSet(true);
    }
  }

}

