/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.kromatik.dasshy.thrift.model;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TJobState implements org.apache.thrift.TEnum {
  READY(0),
  PENDING(1),
  RUNNING(2),
  FINISHED(3),
  ERROR(4),
  ABORT(5);

  private final int value;

  private TJobState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TJobState findByValue(int value) { 
    switch (value) {
      case 0:
        return READY;
      case 1:
        return PENDING;
      case 2:
        return RUNNING;
      case 3:
        return FINISHED;
      case 4:
        return ERROR;
      case 5:
        return ABORT;
      default:
        return null;
    }
  }
}
