/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.kromatik.dasshy.thrift.model;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TKafkaOffset implements org.apache.thrift.TEnum {
  AUTO(0),
  SMALLEST(1),
  LARGEST(2);

  private final int value;

  private TKafkaOffset(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TKafkaOffset findByValue(int value) { 
    switch (value) {
      case 0:
        return AUTO;
      case 1:
        return SMALLEST;
      case 2:
        return LARGEST;
      default:
        return null;
    }
  }
}
