/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.kromatik.dasshy.thrift.model;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class TLoaderConfiguration extends org.apache.thrift.TUnion<TLoaderConfiguration, TLoaderConfiguration._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TLoaderConfiguration");
  private static final org.apache.thrift.protocol.TField CASSANDRA_FIELD_DESC = new org.apache.thrift.protocol.TField("cassandra", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField CUSTOM_FIELD_DESC = new org.apache.thrift.protocol.TField("custom", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CASSANDRA((short)1, "cassandra"),
    CUSTOM((short)2, "custom");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CASSANDRA
          return CASSANDRA;
        case 2: // CUSTOM
          return CUSTOM;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CASSANDRA, new org.apache.thrift.meta_data.FieldMetaData("cassandra", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TCassandraLoaderConfiguration.class)));
    tmpMap.put(_Fields.CUSTOM, new org.apache.thrift.meta_data.FieldMetaData("custom", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TCustomConfiguration.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TLoaderConfiguration.class, metaDataMap);
  }

  public TLoaderConfiguration() {
    super();
  }

  public TLoaderConfiguration(_Fields setField, Object value) {
    super(setField, value);
  }

  public TLoaderConfiguration(TLoaderConfiguration other) {
    super(other);
  }
  public TLoaderConfiguration deepCopy() {
    return new TLoaderConfiguration(this);
  }

  public static TLoaderConfiguration cassandra(TCassandraLoaderConfiguration value) {
    TLoaderConfiguration x = new TLoaderConfiguration();
    x.setCassandra(value);
    return x;
  }

  public static TLoaderConfiguration custom(TCustomConfiguration value) {
    TLoaderConfiguration x = new TLoaderConfiguration();
    x.setCustom(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case CASSANDRA:
        if (value instanceof TCassandraLoaderConfiguration) {
          break;
        }
        throw new ClassCastException("Was expecting value of type TCassandraLoaderConfiguration for field 'cassandra', but got " + value.getClass().getSimpleName());
      case CUSTOM:
        if (value instanceof TCustomConfiguration) {
          break;
        }
        throw new ClassCastException("Was expecting value of type TCustomConfiguration for field 'custom', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case CASSANDRA:
          if (field.type == CASSANDRA_FIELD_DESC.type) {
            TCassandraLoaderConfiguration cassandra;
            cassandra = new TCassandraLoaderConfiguration();
            cassandra.read(iprot);
            return cassandra;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case CUSTOM:
          if (field.type == CUSTOM_FIELD_DESC.type) {
            TCustomConfiguration custom;
            custom = new TCustomConfiguration();
            custom.read(iprot);
            return custom;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case CASSANDRA:
        TCassandraLoaderConfiguration cassandra = (TCassandraLoaderConfiguration)value_;
        cassandra.write(oprot);
        return;
      case CUSTOM:
        TCustomConfiguration custom = (TCustomConfiguration)value_;
        custom.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case CASSANDRA:
          TCassandraLoaderConfiguration cassandra;
          cassandra = new TCassandraLoaderConfiguration();
          cassandra.read(iprot);
          return cassandra;
        case CUSTOM:
          TCustomConfiguration custom;
          custom = new TCustomConfiguration();
          custom.read(iprot);
          return custom;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case CASSANDRA:
        TCassandraLoaderConfiguration cassandra = (TCassandraLoaderConfiguration)value_;
        cassandra.write(oprot);
        return;
      case CUSTOM:
        TCustomConfiguration custom = (TCustomConfiguration)value_;
        custom.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case CASSANDRA:
        return CASSANDRA_FIELD_DESC;
      case CUSTOM:
        return CUSTOM_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public TCassandraLoaderConfiguration getCassandra() {
    if (getSetField() == _Fields.CASSANDRA) {
      return (TCassandraLoaderConfiguration)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'cassandra' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setCassandra(TCassandraLoaderConfiguration value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.CASSANDRA;
    value_ = value;
  }

  public TCustomConfiguration getCustom() {
    if (getSetField() == _Fields.CUSTOM) {
      return (TCustomConfiguration)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'custom' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setCustom(TCustomConfiguration value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.CUSTOM;
    value_ = value;
  }

  public boolean isSetCassandra() {
    return setField_ == _Fields.CASSANDRA;
  }


  public boolean isSetCustom() {
    return setField_ == _Fields.CUSTOM;
  }


  public boolean equals(Object other) {
    if (other instanceof TLoaderConfiguration) {
      return equals((TLoaderConfiguration)other);
    } else {
      return false;
    }
  }

  public boolean equals(TLoaderConfiguration other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(TLoaderConfiguration other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
