/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.kromatik.dasshy.thrift.model;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TStageType implements org.apache.thrift.TEnum {
  EXTRACTOR(0),
  TRANSFORMER(1),
  LOADER(2);

  private final int value;

  private TStageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TStageType findByValue(int value) { 
    switch (value) {
      case 0:
        return EXTRACTOR;
      case 1:
        return TRANSFORMER;
      case 2:
        return LOADER;
      default:
        return null;
    }
  }
}
